SELECT * FROM Composer LIMIT 5;
SELECT * FROM Corpus LIMIT 5;
SELECT * FROM Measure LIMIT 5;
SELECT * FROM Part LIMIT 5;
SELECT * FROM Note LIMIT 5;
SELECT * FROM Trigram LIMIT 5;
SELECT * FROM Interval LIMIT 5;
